import { Leader } from './leader';

export var LEADERS: Leader[] = [
{	id:	1	,	name:	"	Ashraf Ghani	"	,	title:	"	President	of	 Afghanistan	"	}	,
{	id:	2	,	name:	"	Bujar Nishani	"	,	title:	"	President	of	 Albania	"	}	,
{	id:	3	,	name:	"	Abdelaziz Bouteflika	"	,	title:	"	President	of	 Algeria	"	}	,
{	id:	4	,	name:	"	José Eduardo dos Santos	"	,	title:	"	President	of	 Angola	"	}	,
{	id:	5	,	name:	"	Mauricio Macri	"	,	title:	"	President	of	 Argentina	"	}	,
{	id:	6	,	name:	"	Serzh Sargsyan	"	,	title:	"	President	of	 Armenia	"	}	,
{	id:	7	,	name:	"	Alexander Van der Bellen	"	,	title:	"	President	of	 Austria	"	}	,
{	id:	8	,	name:	"	Ilham Aliyev	"	,	title:	"	President	of	 Azerbaijan	"	}	,
{	id:	9	,	name:	"	Abdul Hamid	"	,	title:	"	President	of	 Bangladesh	"	}	,
{	id:	10	,	name:	"	Alexander Lukashenko	"	,	title:	"	President	of	 Belarus	"	}	,
{	id:	11	,	name:	"	Patrice Talon	"	,	title:	"	President	of	 Benin	"	}	,
{	id:	12	,	name:	"	Evo Morales	"	,	title:	"	President	of	 Bolivia	"	}	,
{	id:	13	,	name:	"	Mladen Ivanić	"	,	title:	"	Chairman	of	 Bosnia and Herzegovina	"	}	,
{	id:	14	,	name:	"	Ian Khama	"	,	title:	"	President	of	 Botswana	"	}	,
{	id:	15	,	name:	"	Michel Temer	"	,	title:	"	President	of	 Brazil	"	}	,
{	id:	16	,	name:	"	Rumen Radev	"	,	title:	"	President	of	 Bulgaria	"	}	,
{	id:	17	,	name:	"	Roch Marc Christian Kaboré	"	,	title:	"	President	of	 Burkina Faso	"	}	,
{	id:	18	,	name:	"	Pierre Nkurunziza	"	,	title:	"	President	of	 Burundi	"	}	,
{	id:	19	,	name:	"	Paul Biya	"	,	title:	"	President	of	 Cameroon	"	}	,
{	id:	20	,	name:	"	Jorge Carlos Fonseca	"	,	title:	"	President	of	 Cape Verde	"	}	,
{	id:	21	,	name:	"	Faustin-Archange Touadéra	"	,	title:	"	President	of	 Central African Republic	"	}	,
{	id:	22	,	name:	"	Idriss Déby	"	,	title:	"	President	of	 Chad	"	}	,
{	id:	23	,	name:	"	Michelle Bachelet	"	,	title:	"	President	of	 Chile	"	}	,
{	id:	24	,	name:	"	Xi Jinping	"	,	title:	"	President	of	 China	"	}	,
{	id:	25	,	name:	"	Juan Manuel Santos	"	,	title:	"	President	of	 Colombia	"	}	,
{	id:	26	,	name:	"	Azali Assoumani	"	,	title:	"	President	of	 Comoros	"	}	,
{	id:	27	,	name:	"	Joseph Kabila	"	,	title:	"	President	of	 Congo, the Democratic Republic of the	"	}	,
{	id:	28	,	name:	"	Denis Sassou Nguesso	"	,	title:	"	President	of	 Congo, Republic of the	"	}	,
{	id:	29	,	name:	"	Luis Guillermo Solís	"	,	title:	"	President	of	 Costa Rica	"	}	,
{	id:	30	,	name:	"	Kolinda Grabar-Kitarović	"	,	title:	"	President	of	 Croatia	"	}	,
{	id:	31	,	name:	"	Raúl Castro	"	,	title:	"	President	of	 Cuba	"	}	,
{	id:	32	,	name:	"	Nicos Anastasiades	"	,	title:	"	President	of	 Cyprus	"	}	,
{	id:	33	,	name:	"	Miloš Zeman	"	,	title:	"	President	of	 Czech Republic	"	}	,
{	id:	34	,	name:	"	Charles Savarin	"	,	title:	"	President	of	 Dominica	"	}	,
{	id:	35	,	name:	"	Danilo Medina	"	,	title:	"	President	of	 Dominican Republic	"	}	,
{	id:	36	,	name:	"	Francisco Guterres	"	,	title:	"	President	of	 East Timor	"	}	,
{	id:	37	,	name:	"	Lenin Moreno	"	,	title:	"	President	of	 Ecuador	"	}	,
{	id:	38	,	name:	"	Abdel Fattah el-Sisi	"	,	title:	"	President	of	 Egypt	"	}	,
{	id:	39	,	name:	"	Salvador Sánchez Cerén	"	,	title:	"	President	of	 El Salvador	"	}	,
{	id:	40	,	name:	"	Teodoro Obiang Nguema Mbasogo	"	,	title:	"	President	of	 Equatorial Guinea	"	}	,
{	id:	41	,	name:	"	Isaias Afwerki	"	,	title:	"	President	of	 Eritrea	"	}	,
{	id:	42	,	name:	"	Kersti Kaljulaid	"	,	title:	"	President	of	 Estonia	"	}	,
{	id:	43	,	name:	"	Mulatu Teshome	"	,	title:	"	President	of	 Ethiopia	"	}	,
{	id:	44	,	name:	"	George Konrote	"	,	title:	"	President	of	 Fiji	"	}	,
{	id:	45	,	name:	"	Sauli Niinistö	"	,	title:	"	President	of	 Finland	"	}	,
{	id:	46	,	name:	"	Emmanuel Macron	"	,	title:	"	President	of	 France	"	}	,
{	id:	47	,	name:	"	Ali Bongo Ondimba	"	,	title:	"	President	of	 Gabon	"	}	,
{	id:	48	,	name:	"	Adama Barrow	"	,	title:	"	President	of	 Gambia	"	}	,
{	id:	49	,	name:	"	Giorgi Margvelashvili	"	,	title:	"	President	of	 Georgia	"	}	,
{	id:	50	,	name:	"	Frank-Walter Steinmeier	"	,	title:	"	Federal President	of	 Germany	"	}	,
{	id:	51	,	name:	"	John Dramani Mahama	"	,	title:	"	President	of	 Ghana	"	}	,
{	id:	52	,	name:	"	Prokopis Pavlopoulos	"	,	title:	"	President	of	 Greece	"	}	,
{	id:	53	,	name:	"	Jimmy Morales	"	,	title:	"	President	of	 Guatemala	"	}	,
{	id:	54	,	name:	"	Alpha Condé	"	,	title:	"	Acting President	of	 Guinea	"	}	,
{	id:	55	,	name:	"	José Mário Vaz	"	,	title:	"	President	of	 Guinea-Bissau	"	}	,
{	id:	56	,	name:	"	David Granger	"	,	title:	"	President	of	 Guyana	"	}	,
{	id:	57	,	name:	"	Jovenel Moïse	"	,	title:	"	President	of	 Haiti	"	}	,
{	id:	58	,	name:	"	Juan Orlando Hernández	"	,	title:	"	President	of	 Honduras	"	}	,
{	id:	59	,	name:	"	János Áder	"	,	title:	"	President	of	 Hungary	"	}	,
{	id:	60	,	name:	"	Guðni Th. Jóhannesson	"	,	title:	"	President	of	 Iceland	"	}	,
{	id:	61	,	name:	"	Pranab Mukherjee	"	,	title:	"	President	of	 India	"	}	,
{	id:	62	,	name:	"	Joko Widodo	"	,	title:	"	President	of	 Indonesia	"	}	,
{	id:	63	,	name:	"	Hassan Rouhani	"	,	title:	"	President	of	 Iran	"	}	,
{	id:	64	,	name:	"	Fuad Masum	"	,	title:	"	President	of	 Iraq	"	}	,
{	id:	65	,	name:	"	Michael D. Higgins	"	,	title:	"	President	of	 Ireland	"	}	,
{	id:	66	,	name:	"	Reuven Rivlin	"	,	title:	"	President	of	 Israel	"	}	,
{	id:	67	,	name:	"	Sergio Mattarella	"	,	title:	"	President	of	 Italy	"	}	,
{	id:	68	,	name:	"	Alassane Ouattara	"	,	title:	"	President	of	 Ivory Coast	"	}	,
{	id:	69	,	name:	"	Nursultan Nazarbayev	"	,	title:	"	President	of	 Kazakhstan	"	}	,
{	id:	70	,	name:	"	Uhuru Kenyatta	"	,	title:	"	President	of	 Kenya	"	}	,
{	id:	71	,	name:	"	Taneti Mamau	"	,	title:	"	President	of	 Kiribati	"	}	,
{	id:	72	,	name:	"	Almazbek Atambayev	"	,	title:	"	President	of	 Kyrgyzstan	"	}	,
{	id:	73	,	name:	"	Bounnhang Vorachith	"	,	title:	"	President	of	 Laos	"	}	,
{	id:	74	,	name:	"	Raimonds Vējonis	"	,	title:	"	President	of	 Latvia	"	}	,
{	id:	75	,	name:	"	Michel Aoun	"	,	title:	"	President	of	 Lebanon	"	}	,
{	id:	76	,	name:	"	Ellen Johnson Sirleaf	"	,	title:	"	President	of	 Liberia	"	}	,
{	id:	77	,	name:	"	Fayez al-Sarraj	"	,	title:	"	Chairman	of	 Libya	"	}	,
{	id:	78	,	name:	"	Dalia Grybauskaitė	"	,	title:	"	President	of	 Lithuania	"	}	,
{	id:	79	,	name:	"	Gjorge Ivanov	"	,	title:	"	President	of	 Macedonia	"	}	,
{	id:	80	,	name:	"	Hery Rajaonarimampianina	"	,	title:	"	President	of	 Madagascar	"	}	,
{	id:	81	,	name:	"	Peter Mutharika	"	,	title:	"	President	of	 Malawi	"	}	,
{	id:	82	,	name:	"	Abdulla Yameen	"	,	title:	"	President	of	 Maldives	"	}	,
{	id:	83	,	name:	"	Ibrahim Boubacar Keïta	"	,	title:	"	President	of	 Mali	"	}	,
{	id:	84	,	name:	"	Marie Louise Coleiro Preca	"	,	title:	"	President	of	 Malta	"	}	,
{	id:	85	,	name:	"	Hilda Heine	"	,	title:	"	President	of	 Marshall Islands	"	}	,
{	id:	86	,	name:	"	Mohamed Ould Abdel Aziz	"	,	title:	"	President	of	 Mauritania	"	}	,
{	id:	87	,	name:	"	Ameenah Gurib	"	,	title:	"	President	of	 Mauritius	"	}	,
{	id:	88	,	name:	"	Enrique Peña Nieto	"	,	title:	"	President	of	 Mexico	"	}	,
{	id:	89	,	name:	"	Peter M. Christian	"	,	title:	"	President	of	 Federated States of Micronesia	"	}	,
{	id:	90	,	name:	"	Nicolae Timofti	"	,	title:	"	President	of	 Moldova	"	}	,
{	id:	91	,	name:	"	Tsakhiagiin Elbegdorj	"	,	title:	"	President	of	 Mongolia	"	}	,
{	id:	92	,	name:	"	Filip Vujanović	"	,	title:	"	President	of	 Montenegro	"	}	,
{	id:	93	,	name:	"	Filipe Nyusi	"	,	title:	"	President	of	 Mozambique	"	}	,
{	id:	94	,	name:	"	Htin Kyaw	"	,	title:	"	President	of	 Myanmar	"	}	,
{	id:	95	,	name:	"	Hage Geingob	"	,	title:	"	President	of	 Namibia	"	}	,
{	id:	96	,	name:	"	Baron Waqa	"	,	title:	"	President	of	 Nauru	"	}	,
{	id:	97	,	name:	"	Bidya Devi Bhandari	"	,	title:	"	President	of	   Nepal	"	}	,
{	id:	98	,	name:	"	Daniel Ortega	"	,	title:	"	President	of	 Nicaragua	"	}	,
{	id:	99	,	name:	"	Mahamadou Issoufou	"	,	title:	"	President	of	 Niger	"	}	,
{	id:	100	,	name:	"	Muhammadu Buhari	"	,	title:	"	President	of	 Nigeria	"	}	,
{	id:	101	,	name:	"	Kim Jong-un	"	,	title:	"	President	of	 North Korea	"	}	,
{	id:	102	,	name:	"	Mamnoon Hussain	"	,	title:	"	President	of	 Pakistan	"	}	,
{	id:	103	,	name:	"	Tommy Remengesau	"	,	title:	"	President	of	 Palau	"	}	,
{	id:	104	,	name:	"	Mahmoud Abbas	"	,	title:	"	President	of	 Palestine	"	}	,
{	id:	105	,	name:	"	Juan Carlos Varela	"	,	title:	"	President	of	 Panama	"	}	,
{	id:	106	,	name:	"	Horacio Cartes	"	,	title:	"	President	of	 Paraguay	"	}	,
{	id:	107	,	name:	"	Pedro Pablo Kuczynski	"	,	title:	"	President	of	 Peru	"	}	,
{	id:	108	,	name:	"	Rodrigo Duterte	"	,	title:	"	President	of	 Philippines	"	}	,
{	id:	109	,	name:	"	Andrzej Duda	"	,	title:	"	President	of	 Poland	"	}	,
{	id:	110	,	name:	"	Marcelo Rebelo de Sousa	"	,	title:	"	President	of	 Portugal	"	}	,
{	id:	111	,	name:	"	Klaus Iohannis	"	,	title:	"	President	of	 Romania	"	}	,
{	id:	112	,	name:	"	Vladimir Putin	"	,	title:	"	President	of	 Russia	"	}	,
{	id:	113	,	name:	"	Paul Kagame	"	,	title:	"	President	of	 Rwanda	"	}	,
{	id:	114	,	name:	"	Marino Riccardi Fabio Berardi	"	,	title:	"	Captain Regent	of	 San Marino	"	}	,
{	id:	115	,	name:	"	Evaristo Carvalho	"	,	title:	"	President	of	 São Tomé and Príncipe	"	}	,
{	id:	116	,	name:	"	Macky Sall	"	,	title:	"	President	of	 Senegal	"	}	,
{	id:	117	,	name:	"	Tomislav Nikolić	"	,	title:	"	President	of	 Serbia	"	}	,
{	id:	118	,	name:	"	James Michel	"	,	title:	"	President	of	 Seychelles	"	}	,
{	id:	119	,	name:	"	Ernest Bai Koroma	"	,	title:	"	President	of	 Sierra Leone	"	}	,
{	id:	120	,	name:	"	Tony Tan	"	,	title:	"	President	of	 Singapore	"	}	,
{	id:	121	,	name:	"	Andrej Kiska	"	,	title:	"	President	of	 Slovakia	"	}	,
{	id:	122	,	name:	"	Borut Pahor	"	,	title:	"	President	of	 Slovenia	"	}	,
{	id:	123	,	name:	"	Hassan Sheikh Mohamud	"	,	title:	"	President	of	 Somalia	"	}	,
{	id:	124	,	name:	"	Jacob Zuma	"	,	title:	"	President	of	 South Africa	"	}	,
{	id:	125	,	name:	"	Moon Jae-in	"	,	title:	"	President	of	 South Korea	"	}	,
{	id:	126	,	name:	"	Salva Kiir Mayardit	"	,	title:	"	President	of	 South Sudan	"	}	,
{	id:	127	,	name:	"	Maithripala Sirisena	"	,	title:	"	President	of	 Sri Lanka	"	}	,
{	id:	128	,	name:	"	Omar al-Bashir	"	,	title:	"	President	of	 Sudan	"	}	,
{	id:	129	,	name:	"	Dési Bouterse	"	,	title:	"	President	of	 Suriname	"	}	,
{	id:	130	,	name:	"	Johann Schneider-Ammann	"	,	title:	"	President	of	  Switzerland	"	}	,
{	id:	131	,	name:	"	Bashar al-Assad	"	,	title:	"	President	of	 Syria	"	}	,
{	id:	132	,	name:	"	Emomalii Rahmon	"	,	title:	"	President	of	 Tajikistan	"	}	,
{	id:	133	,	name:	"	Jakaya Kikwete	"	,	title:	"	President	of	 Tanzania	"	}	,
{	id:	134	,	name:	"	Faure Gnassingbé	"	,	title:	"	President	of	 Togo	"	}	,
{	id:	135	,	name:	"	Anthony Carmona	"	,	title:	"	President	of	 Trinidad and Tobago	"	}	,
{	id:	136	,	name:	"	Beji Caid Essebsi	"	,	title:	"	President	of	 Tunisia	"	}	,
{	id:	137	,	name:	"	Recep Tayyip Erdoğan	"	,	title:	"	President	of	 Turkey	"	}	,
{	id:	138	,	name:	"	Gurbanguly Berdimuhamedow	"	,	title:	"	President	of	 Turkmenistan	"	}	,
{	id:	139	,	name:	"	Yoweri Museveni	"	,	title:	"	President	of	 Uganda	"	}	,
{	id:	140	,	name:	"	Petro Poroshenko	"	,	title:	"	President	of	 Ukraine	"	}	,
{	id:	141	,	name:	"	Donald Trump	"	,	title:	"	President	of	 United States	"	}	,
{	id:	142	,	name:	"	Tabaré Vázquez	"	,	title:	"	President	of	 Uruguay	"	}	,
{	id:	143	,	name:	"	Shavkat Mirziyoyev	"	,	title:	"	President	of	 Uzbekistan	"	}	,
{	id:	144	,	name:	"	Baldwin Lonsdale	"	,	title:	"	President	of	 Vanuatu	"	}	,
{	id:	145	,	name:	"	Nicolás Maduro	"	,	title:	"	President	of	 Venezuela	"	}	,
{	id:	146	,	name:	"	Trần Đại Quang	"	,	title:	"	President	of	 Vietnam	"	}	,
{	id:	147	,	name:	"	Abd Rabbuh Mansur Hadi	"	,	title:	"	President	of	 Yemen	"	}	,
{	id:	148	,	name:	"	Edgar Lungu	"	,	title:	"	President	of	 Zambia	"	}	,
{	id:	149	,	name:	"	Robert Mugabe	"	,	title:	"	President	of	 Zimbabwe	"	}	,
{	id:	150	,	name:	"	Edi Rama	"	,	title:	"	Prime Minister	of	 Albania	"	}	,
{	id:	151	,	name:	"	Abdelmadjid Tebboune	"	,	title:	"	Prime Minister	of	 Algeria	"	}	,
{	id:	152	,	name:	"	Antoni Martí	"	,	title:	"	Head of Government	of	 Andorra	"	}	,
{	id:	153	,	name:	"	Gaston Browne	"	,	title:	"	Prime Minister	of	 Antigua and Barbuda	"	}	,
{	id:	154	,	name:	"	Karen Karapetyan	"	,	title:	"	Prime Minister	of	 Armenia	"	}	,
{	id:	155	,	name:	"	Malcolm Turnbull	"	,	title:	"	Prime Minister	of	 Australia	"	}	,
{	id:	156	,	name:	"	Christian Kern	"	,	title:	"	Federal Chancellor	of	 Austria	"	}	,
{	id:	157	,	name:	"	Artur Rasizade	"	,	title:	"	Prime Minister	of	 Azerbaijan	"	}	,
{	id:	158	,	name:	"	Hubert Minnis	"	,	title:	"	Prime Minister	of	 Bahamas	"	}	,
{	id:	159	,	name:	"	Prince Khalifa bin Salman Al Khalifa	"	,	title:	"	Prime Minister	of	 Bahrain	"	}	,
{	id:	160	,	name:	"	Sheikh Hasina	"	,	title:	"	Prime Minister	of	 Bangladesh	"	}	,
{	id:	161	,	name:	"	Freundel Stuart	"	,	title:	"	Prime Minister	of	 Barbados	"	}	,
{	id:	162	,	name:	"	Andrei Kobyakov	"	,	title:	"	Prime Minister	of	 Belarus	"	}	,
{	id:	163	,	name:	"	Charles Michel	"	,	title:	"	Prime Minister	of	 Belgium	"	}	,
{	id:	164	,	name:	"	Dean Barrow	"	,	title:	"	Prime Minister	of	 Belize	"	}	,
{	id:	165	,	name:	"	Michael Dunkley	"	,	title:	"	Premier	of	 Bermuda	"	}	,
{	id:	166	,	name:	"	Tshering Tobgay	"	,	title:	"	Prime Minister	of	 Bhutan	"	}	,
{	id:	167	,	name:	"	Denis Zvizdić	"	,	title:	"	Chairman of the Council of Ministers	of	 Bosnia and Herzegovina	"	}	,
{	id:	168	,	name:	"	Hassanal Bolkiah	"	,	title:	"	Prime Minister	of	 Brunei	"	}	,
{	id:	169	,	name:	"	Boyko Borisov	"	,	title:	"	Prime Minister	of	 Bulgaria	"	}	,
{	id:	170	,	name:	"	Paul Kaba Thieba	"	,	title:	"	Prime Minister	of	 Burkina Faso	"	}	,
{	id:	171	,	name:	"	Hun Sen	"	,	title:	"	Prime Minister	of	 Cambodia	"	}	,
{	id:	172	,	name:	"	Philémon Yang	"	,	title:	"	Prime Minister	of	 Cameroon	"	}	,
{	id:	173	,	name:	"	Justin Trudeau	"	,	title:	"	Prime Minister	of	 Canada	"	}	,
{	id:	174	,	name:	"	Ulisses Correia e Silva	"	,	title:	"	Prime Minister	of	 Cape Verde	"	}	,
{	id:	175	,	name:	"	Simplice Sarandji	"	,	title:	"	Prime Minister	of	 Central African Republic	"	}	,
{	id:	176	,	name:	"	Albert Pahimi Padacké	"	,	title:	"	Prime Minister	of	 Chad	"	}	,
{	id:	177	,	name:	"	Li Keqiang	"	,	title:	"	Premier of the State Council	of	 China	"	}	,
{	id:	178	,	name:	"	Bruno Tshibala	"	,	title:	"	Prime Minister	of	 Congo, the Democratic Republic of the	"	}	,
{	id:	179	,	name:	"	Clément Mouamba	"	,	title:	"	Prime Minister	of	 Congo, Republic of the	"	}	,
{	id:	180	,	name:	"	Andrej Plenković	"	,	title:	"	Prime Minister	of	 Croatia	"	}	,
{	id:	181	,	name:	"	Raúl Castro	"	,	title:	"	President of the Council of Ministers	of	 Cuba	"	}	,
{	id:	182	,	name:	"	Bohuslav Sobotka	"	,	title:	"	Prime Minister	of	 Czech Republic	"	}	,
{	id:	183	,	name:	"	Lars Løkke Rasmussen	"	,	title:	"	Prime Minister	of	 Denmark	"	}	,
{	id:	184	,	name:	"	Abdoulkader Kamil Mohamed	"	,	title:	"	Prime Minister	of	 Djibouti	"	}	,
{	id:	185	,	name:	"	Roosevelt Skerrit	"	,	title:	"	Prime Minister	of	 Dominica	"	}	,
{	id:	186	,	name:	"	Rui Maria de Araújo	"	,	title:	"	Prime Minister	of	 East Timor	"	}	,
{	id:	187	,	name:	"	Sherif Ismail	"	,	title:	"	Prime Minister	of	 Egypt	"	}	,
{	id:	188	,	name:	"	Francisco Pascual Obama Asue	"	,	title:	"	Prime Minister	of	 Equatorial Guinea	"	}	,
{	id:	189	,	name:	"	Jüri Ratas	"	,	title:	"	Prime Minister	of	 Estonia	"	}	,
{	id:	190	,	name:	"	Hailemariam Desalegn	"	,	title:	"	Prime Minister	of	 Ethiopia	"	}	,
{	id:	191	,	name:	"	Frank Bainimarama	"	,	title:	"	Prime Minister	of	 Fiji	"	}	,
{	id:	192	,	name:	"	Juha Sipilä	"	,	title:	"	Prime Minister	of	 Finland	"	}	,
{	id:	193	,	name:	"	Édouard Philippe	"	,	title:	"	Prime Minister	of	 France	"	}	,
{	id:	194	,	name:	"	Emmanuel Issoze-Ngondet	"	,	title:	"	Prime Minister	of	 Gabon	"	}	,
{	id:	195	,	name:	"	Giorgi Kvirikashvili	"	,	title:	"	Prime Minister	of	 Georgia	"	}	,
{	id:	196	,	name:	"	Angela Merkel	"	,	title:	"	Federal Chancellor	of	 Germany	"	}	,
{	id:	197	,	name:	"	Alexis Tsipras	"	,	title:	"	Prime Minister	of	 Greece	"	}	,
{	id:	198	,	name:	"	Keith Mitchell	"	,	title:	"	Prime Minister	of	 Grenada	"	}	,
{	id:	199	,	name:	"	Mamady Youla	"	,	title:	"	Prime Minister	of	 Guinea	"	}	,
{	id:	200	,	name:	"	Umaro Sissoco Embaló	"	,	title:	"	Prime Minister	of	 Guinea-Bissau	"	}	,
{	id:	201	,	name:	"	Moses Nagamootoo	"	,	title:	"	Prime Minister	of	 Guyana	"	}	,
{	id:	202	,	name:	"	Jack Guy Lafontant	"	,	title:	"	Prime Minister	of	 Haiti	"	}	,
{	id:	203	,	name:	"	Viktor Orbán	"	,	title:	"	Prime Minister	of	 Hungary	"	}	,
{	id:	204	,	name:	"	Bjarni Benediktsson	"	,	title:	"	Prime Minister	of	 Iceland	"	}	,
{	id:	205	,	name:	"	Narendra Modi	"	,	title:	"	Prime Minister	of	 India	"	}	,
{	id:	206	,	name:	"	Haider al-Abadi	"	,	title:	"	Prime Minister	of	 Iraq	"	}	,
{	id:	207	,	name:	"	Leo Varadkar	"	,	title:	"	Taoiseach	of	 Ireland	"	}	,
{	id:	208	,	name:	"	Benjamin Netanyahu	"	,	title:	"	Prime Minister	of	 Israel	"	}	,
{	id:	209	,	name:	"	Paolo Gentiloni	"	,	title:	"	President of the Council of Ministers	of	 Italy	"	}	,
{	id:	210	,	name:	"	Amadou Gon Coulibaly	"	,	title:	"	Prime Minister	of	 Ivory Coast	"	}	,
{	id:	211	,	name:	"	Andrew Holness	"	,	title:	"	Prime Minister	of	 Jamaica	"	}	,
{	id:	212	,	name:	"	Shinzō Abe	"	,	title:	"	Prime Minister	of	 Japan	"	}	,
{	id:	213	,	name:	"	Hani Al-Mulki	"	,	title:	"	Prime Minister	of	 Jordan	"	}	,
{	id:	214	,	name:	"	Bakhytzhan Sagintayev	"	,	title:	"	Prime Minister	of	 Kazakhstan	"	}	,
{	id:	215	,	name:	"	Sheikh Jaber Al-Mubarak Al-Hamad Al-Sabah	"	,	title:	"	Prime Minister	of	 Kuwait	"	}	,
{	id:	216	,	name:	"	Sooronbay Jeenbekov	"	,	title:	"	Prime Minister	of	 Kyrgyzstan	"	}	,
{	id:	217	,	name:	"	Thongloun Sisoulith	"	,	title:	"	Prime Minister	of	 Laos	"	}	,
{	id:	218	,	name:	"	Māris Kučinskis	"	,	title:	"	Prime Minister	of	 Latvia	"	}	,
{	id:	219	,	name:	"	Saad Hariri	"	,	title:	"	President of the Council of Ministers	of	 Lebanon	"	}	,
{	id:	220	,	name:	"	Tom Thabane	"	,	title:	"	Prime Minister	of	 Lesotho	"	}	,
{	id:	221	,	name:	"	Fayez al-Sarraj	"	,	title:	"	Prime Minister	of	 Libya	"	}	,
{	id:	222	,	name:	"	Adrian Hasler	"	,	title:	"	Head of Government	of	 Liechtenstein	"	}	,
{	id:	223	,	name:	"	Saulius Skvernelis	"	,	title:	"	Prime Minister	of	 Lithuania	"	}	,
{	id:	224	,	name:	"	Xavier Bettel	"	,	title:	"	Prime Minister	of	 Luxembourg	"	}	,
{	id:	225	,	name:	"	Zoran Zaev	"	,	title:	"	President of the Government	of	 Macedonia	"	}	,
{	id:	226	,	name:	"	Olivier Mahafaly Solonandrasana	"	,	title:	"	Prime Minister	of	 Madagascar	"	}	,
{	id:	227	,	name:	"	Najib Razak	"	,	title:	"	Prime Minister	of	 Malaysia	"	}	,
{	id:	228	,	name:	"	Abdoulaye Idrissa Maïga	"	,	title:	"	Prime Minister	of	 Mali	"	}	,
{	id:	229	,	name:	"	Joseph Muscat	"	,	title:	"	Prime Minister	of	 Malta	"	}	,
{	id:	230	,	name:	"	Yahya Ould Hademine	"	,	title:	"	Prime Minister	of	 Mauritania	"	}	,
{	id:	231	,	name:	"	Pravind Jugnauth	"	,	title:	"	Prime Minister	of	 Mauritius	"	}	,
{	id:	232	,	name:	"	Pavel Filip	"	,	title:	"	Prime Minister	of	 Moldova	"	}	,
{	id:	233	,	name:	"	Serge Telle	"	,	title:	"	Minister of State	of	 Monaco	"	}	,
{	id:	234	,	name:	"	Jargaltulgyn Erdenebat	"	,	title:	"	Prime Minister	of	 Mongolia	"	}	,
{	id:	235	,	name:	"	Duško Marković	"	,	title:	"	Prime Minister	of	 Montenegro	"	}	,
{	id:	236	,	name:	"	Saadeddine Othmani	"	,	title:	"	Head of Government	of	 Morocco	"	}	,
{	id:	237	,	name:	"	Carlos Agostinho do Rosário	"	,	title:	"	Prime Minister	of	 Mozambique	"	}	,
{	id:	238	,	name:	"	Aung San Suu Kyi	"	,	title:	"	State Counsellor	of	 Myanmar	"	}	,
{	id:	239	,	name:	"	Saara Kuugongelwa	"	,	title:	"	Prime Minister	of	 Namibia	"	}	,
{	id:	240	,	name:	"	Sher Bahadur Deuba	"	,	title:	"	Prime Minister	of	   Nepal	"	}	,
{	id:	241	,	name:	"	Mark Rutte	"	,	title:	"	Prime Minister	of	 Netherlands	"	}	,
{	id:	242	,	name:	"	Bill English	"	,	title:	"	Prime Minister	of	 New Zealand	"	}	,
{	id:	243	,	name:	"	Brigi Rafini	"	,	title:	"	Prime Minister	of	 Niger	"	}	,
{	id:	244	,	name:	"	Pak Pong-ju	"	,	title:	"	Premier of the Cabinet	of	 North Korea	"	}	,
{	id:	245	,	name:	"	Erna Solberg	"	,	title:	"	Prime Minister	of	 Norway	"	}	,
{	id:	246	,	name:	"	Qaboos bin Said	"	,	title:	"	Prime Minister	of	 Oman	"	}	,
{	id:	247	,	name:	"	Nawaz Sharif	"	,	title:	"	Prime Minister	of	 Pakistan	"	}	,
{	id:	248	,	name:	"	Rami Hamdallah	"	,	title:	"	Prime Minister	of	 Palestine	"	}	,
{	id:	249	,	name:	"	Peter O'Neill	"	,	title:	"	Prime Minister	of	 Papua New Guinea	"	}	,
{	id:	250	,	name:	"	Fernando Zavala	"	,	title:	"	President of the Council of Ministers	of	 Peru	"	}	,
{	id:	251	,	name:	"	Beata Szydło	"	,	title:	"	Chairman of the Council of Ministers	of	 Poland	"	}	,
{	id:	252	,	name:	"	António Costa	"	,	title:	"	Prime Minister	of	 Portugal	"	}	,
{	id:	253	,	name:	"	Sheikh Abdullah bin Nasser bin Khalifa Al Thani	"	,	title:	"	Prime Minister	of	 Qatar	"	}	,
{	id:	254	,	name:	"	Sorin Grindeanu	"	,	title:	"	Prime Minister	of	 Romania	"	}	,
{	id:	255	,	name:	"	Dmitry Medvedev	"	,	title:	"	Chairman of the Government	of	 Russia	"	}	,
{	id:	256	,	name:	"	Anastase Murekezi	"	,	title:	"	Prime Minister	of	 Rwanda	"	}	,
{	id:	257	,	name:	"	Timothy Harris	"	,	title:	"	Prime Minister	of	 Saint Kitts and Nevis	"	}	,
{	id:	258	,	name:	"	Allen Chastanet	"	,	title:	"	Prime Minister	of	 Saint Lucia	"	}	,
{	id:	259	,	name:	"	Ralph Gonsalves	"	,	title:	"	Prime Minister	of	 Saint Vincent and the Grenadines	"	}	,
{	id:	260	,	name:	"	Tuilaepa Aiono Sailele Malielegaoi	"	,	title:	"	Prime Minister	of	 Samoa	"	}	,
{	id:	261	,	name:	"	Patrice Trovoada	"	,	title:	"	Prime Minister	of	 São Tomé and Príncipe	"	}	,
{	id:	262	,	name:	"	Salman	"	,	title:	"	Prime Minister	of	 Saudi Arabia	"	}	,
{	id:	263	,	name:	"	Mohamed Dionne	"	,	title:	"	Prime Minister	of	 Senegal	"	}	,
{	id:	264	,	name:	"	Ivica Dačić (acting)	"	,	title:	"	Prime Minister	of	 Serbia	"	}	,
{	id:	265	,	name:	"	Lee Hsien Loong	"	,	title:	"	Prime Minister	of	 Singapore	"	}	,
{	id:	266	,	name:	"	Robert Fico	"	,	title:	"	Prime Minister	of	 Slovakia	"	}	,
{	id:	267	,	name:	"	Miro Cerar	"	,	title:	"	Prime Minister	of	 Slovenia	"	}	,
{	id:	268	,	name:	"	Manasseh Sogavare	"	,	title:	"	Prime Minister	of	 Solomon Islands	"	}	,
{	id:	269	,	name:	"	Hassan Ali Khayre	"	,	title:	"	Prime Minister	of	 Somalia	"	}	,
{	id:	270	,	name:	"	Lee Nak-yeon	"	,	title:	"	Prime Minister	of	 South Korea	"	}	,
{	id:	271	,	name:	"	Mariano Rajoy	"	,	title:	"	President of the Government	of	 Spain	"	}	,
{	id:	272	,	name:	"	Ranil Wickremesinghe	"	,	title:	"	Prime Minister	of	 Sri Lanka	"	}	,
{	id:	273	,	name:	"	Bakri Hassan Saleh	"	,	title:	"	Prime Minister	of	 Sudan	"	}	,
{	id:	274	,	name:	"	Barnabas Sibusiso Dlamini	"	,	title:	"	Prime Minister	of	 Swaziland	"	}	,
{	id:	275	,	name:	"	Stefan Löfven	"	,	title:	"	Prime Minister	of	 Sweden	"	}	,
{	id:	276	,	name:	"	Imad Khamis	"	,	title:	"	Prime Minister	of	 Syria	"	}	,
{	id:	277	,	name:	"	Kokhir Rasulzoda	"	,	title:	"	Prime Minister	of	 Tajikistan	"	}	,
{	id:	278	,	name:	"	Kassim Majaliwa	"	,	title:	"	Prime Minister	of	 Tanzania	"	}	,
{	id:	279	,	name:	"	Prayut Chan-o-cha	"	,	title:	"	Prime Minister	of	 Thailand	"	}	,
{	id:	280	,	name:	"	Komi Sélom Klassou	"	,	title:	"	Prime Minister	of	 Togo	"	}	,
{	id:	281	,	name:	"	Afega Gaualofa	"	,	title:	"	Prime Minister	of	 Tokelau	"	}	,
{	id:	282	,	name:	"	ʻAkilisi Pōhiva	"	,	title:	"	Prime Minister	of	 Tonga	"	}	,
{	id:	283	,	name:	"	Keith Rowley	"	,	title:	"	Prime Minister	of	 Trinidad and Tobago	"	}	,
{	id:	284	,	name:	"	Youssef Chahed	"	,	title:	"	Head of Government	of	 Tunisia	"	}	,
{	id:	285	,	name:	"	Binali Yıldırım	"	,	title:	"	Prime Minister	of	 Turkey	"	}	,
{	id:	286	,	name:	"	Enele Sopoaga	"	,	title:	"	Prime Minister	of	 Tuvalu	"	}	,
{	id:	287	,	name:	"	Ruhakana Rugunda	"	,	title:	"	Prime Minister	of	 Uganda	"	}	,
{	id:	288	,	name:	"	Volodymyr Groysman	"	,	title:	"	Prime Minister	of	 Ukraine	"	}	,
{	id:	289	,	name:	"	Sheikh Mohammed bin Rashid Al Maktoum	"	,	title:	"	Prime Minister	of	 United Arab Emirates	"	}	,
{	id:	290	,	name:	"	Theresa May	"	,	title:	"	Prime Minister	of	 United Kingdom	"	}	,
{	id:	291	,	name:	"	Abdulla Aripov	"	,	title:	"	Prime Minister	of	 Uzbekistan	"	}	,
{	id:	292	,	name:	"	Charlot Salwai	"	,	title:	"	Prime Minister	of	 Vanuatu	"	}	,
{	id:	293	,	name:	"	Cardinal Pietro Parolin	"	,	title:	"	Cardinal Secretary of State	of	  Vatican	"	}	,
{	id:	294	,	name:	"	Nguyễn Xuân Phúc	"	,	title:	"	Prime Minister	of	 Vietnam	"	}	,
{	id:	295	,	name:	"	Ahmed Obeid bin Daghr	"	,	title:	"	Prime Minister	of	 Yemen	"	}	,
{	id:	296	,	name:	"	Hassanal Bolkiah	"	,	title:	"	Sultan	of	Brunei	"	}	,
{	id:	297	,	name:	"	Qaboos bin Said	"	,	title:	"	Sultan	of	Oman	"	}	,
{	id:	298	,	name:	"	Mswati	"	,	title:	"	King	of	Swaziland	"	}	,
{	id:	299	,	name:	"	Salman bin Abdul’aziz	"	,	title:	"	King	of	Saudi Arabia	"	}	
];
